### ISSUE TITLE
Remove use of `webkitStorageInfo` 

### ISSUE THREAD

**Issue by rafaelverger** [raphamorim/nautilus.js#1]
DevTools is already warning about this deprecation:

```
[Deprecation] 'window.webkitStorageInfo' is deprecated. Please use
'navigator.webkitTemporaryStorage' or `navigator.webkitPersistentStorage' instead.
```

**Comment by fmatoss** [comment]
This is a bug, nautilus.js extends `window` with all it's methods, `getConfig`, `resetConfig`, etc all are defined as props of `window`, when it iterates props of `window` in [_.extends](https://github.com/raphamorim/nautilus.js/blob/783f938484ee25aff50c073c83488a0d3688e974/src/utils.js#L2-L14) it will show this warning

**Comment by fmatoss** [comment]
This bug could be identified early if using `strict mode`, `this` value would be `undefined` instead of `window`
