### ISSUE TITLE
Why tabs?

### ISSUE THREAD

**Issue by fititnt** [raphamorim/nautilus.js#5]
Why not 2 spaces?

Good to see:

- https://github.com/feross/standard
- https://google.github.io/styleguide/javascriptguide.xml

**Comment by raphamorim** [comment]
Yep,
It would be nice to have a lint: D
@fititnt can you sent a PR to normalize it?

**Comment by fititnt** [comment]
This is a very big change. I do not want to change the history of your project in Git.

Maybe you do it yourself, or mark this issue as one easy for new people to open source. Maybe sugest someone add one .editorconfig, see http://editorconfig.org/ and then format the code and make the PR.

If you want take more people to open source, just close this issue, and open a new one that explain a bit better, and add tags like `Your First PR`, `First Timers Only` and or see http://up-for-grabs.net/.

This suggestions are from https://github.com/webiwg/webiwg-issues/issues/18

**Comment by raphamorim** [comment]
Closed in #7
